local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   width: 10.0
   height: 10.0
   resolution: 0.05
   rolling_window: true
   static_map: false
